# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23717f140ccac57f80413cd260b73973cb0d7b67a836a8689a2f4d51069244d1abbb6bd22df0a6ac4be887a9def4dee9119606d337dacd5d14b902e49cd68039

test:
  secret_key_base: 6dcda254aa5ff9f6aef000b3cf6bcb90668f360f62138da75ea35d6068f36edc8035c71bc66cf65f839c960869526518094b71249c403438680d16df0ea683f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
